# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "50f74b1ef907fb5c0a54408c7aa5ed2dad14d22c"

[[deps.AlgebraicAgents]]
deps = ["Crayons", "Glob", "InteractiveUtils", "MacroTools", "Random", "UUIDs"]
path = "../.."
uuid = "f6eb0ae3-10fa-40e6-88dd-9006ba45093a"
version = "0.4.0"

    [deps.AlgebraicAgents.extensions]
    AlgebraicAgentsAgentsExt = "Agents"
    AlgebraicAgentsAgentsPlotsExt = ["Agents", "Plots"]
    AlgebraicAgentsAlgebraicDynamicsExt = "AlgebraicDynamics"
    AlgebraicAgentsAlgebraicDynamicsSciMLExt = ["AlgebraicDynamics", "DifferentialEquations"]
    AlgebraicAgentsDataFramesPlotsExt = ["DataFrames", "Plots"]
    AlgebraicAgentsGraphvizExt = "Graphviz_jll"
    AlgebraicAgentsSciMLExt = "DifferentialEquations"
    AlgebraicAgentsSciMLPlotsExt = ["DifferentialEquations", "Plots"]

    [deps.AlgebraicAgents.weakdeps]
    Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
    AlgebraicDynamics = "5fd6ff03-a254-427e-8840-ba658f502e32"
    DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
    DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
    Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
    Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
version = "1.11.0"

[[deps.Crayons]]
git-tree-sha1 = "249fe38abf76d48563e2f4556bebd215aa317e15"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.1.1"

[[deps.Glob]]
git-tree-sha1 = "246c628cec062230b7d183aab88841fa94fcabe9"
uuid = "c27321d9-0574-5035-807b-f59d2c89b15c"
version = "1.5.0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
version = "1.11.0"

[[deps.JuliaSyntaxHighlighting]]
deps = ["StyledStrings"]
uuid = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"
version = "1.12.0"

[[deps.MacroTools]]
git-tree-sha1 = "1e0228a030642014fe5cfe68c2c0a818f9e3f522"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.16"

[[deps.Markdown]]
deps = ["Base64", "JuliaSyntaxHighlighting", "StyledStrings"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
version = "1.11.0"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.StyledStrings]]
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
version = "1.11.0"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
version = "1.11.0"
